name: chirp_addons
description: "Dio logging and pretty JSON addons for the chirp logging package."
version: 0.0.2
homepage:
repository: https://github.com/ahnaf16/chirp_addons

environment:
  sdk: ^3.11.5

dependencies:
  chirp: ^0.9.0
  dio: ^5.9.2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - logging
  - dio-logging
  - pretty-json
  - chirp
